sudo: required
language: java
jdk: oraclejdk11

services:
  - postgresql

before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
  organization: "notheproblem"
  token: $SONAR_TOKEN

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=NoTheProblem_ISA
dist: trusty

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: isaback

